<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:diggs="http://diggsml.org/schemas/3"
    xmlns:gml="http://www.opengis.net/gml/3.2"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:maxVersion="1.1" vc:minVersion="1.0"
    elementFormDefault="qualified" targetNamespace="http://diggsml.org/schemas/3" version="3.0.0">

    <!-- Uncomment to clear validation errors without a master file -->
    <include schemaLocation="../Diggs.xsd"/>


    <import namespace="http://www.opengis.net/gml/3.2" schemaLocation="gml3.2Profile_diggs.xsd"/>
    <import namespace="http://www.w3.org/1999/xlink" schemaLocation="xlinks.xsd"/>

    <element name="LoadTransferPlatform" type="diggs:LoadTransferPlatformType"/>
    <complexType name="LoadTransferPlatformType">
        <complexContent>
            <extension base="diggs:AbstractPlanarSamplingFeatureType">
                <sequence>
                    <element minOccurs="0" name="designLTPRef"/>
                    <element maxOccurs="unbounded" minOccurs="1" name="ltpZone"
                        type="diggs:LTPZonePropertyType"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="LTPZonePropertyType">
        <sequence>
            <element ref="diggs:LTPZone"/>
        </sequence>
    </complexType>
    <element name="LTPZone" type="diggs:LTPZoneType"/>
    <complexType name="LTPZoneType">
        <complexContent>
            <extension base="diggs:AbstractNamedObjectType">
                <sequence>
                    <element minOccurs="0" name="designLTPZoneRef" type="gml:ReferenceType"/>
                    <element name="location" type="diggs:PlanarSurfacePropertyType"/>
                    <element minOccurs="0" name="materialType" type="diggs:LithologyPropertyType"/>
                    <element minOccurs="0" name="elevationCMCCutoff" type="diggs:ElevationType"/>
                    <element minOccurs="0" name="elevationTopLTP" type="diggs:ElevationType"/>
                    <element name="impliedLTPThickness" type="diggs:LengthMeasureType"/>
                    <element maxOccurs="unbounded" minOccurs="0" name="geosynthetic"
                        type="diggs:GeosyntheticPropertyType"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <element name="Geosynthetic" type="diggs:GeosyntheticType"/>
    <complexType name="GeosyntheticType">
        <complexContent>
            <extension base="diggs:AbstractObjectType">
                <sequence>
                    <element minOccurs="0" name="type" type="gml:CodeType">
                        <annotation>
                            <documentation>Identifies the type of geosynthetic used, for example, "geotextile", "geogrid", "geomembrane", etc. Intended to come from a controlled list of terms.</documentation>
                        </annotation>
                    </element>
                    <element minOccurs="0" name="elevation" type="diggs:ElevationType">
                        <annotation>
                            <documentation>The elevation of the geogrid within the zone. Use srsName to specify absolute vertical CRS and/or datumReference to specify local datum type.</documentation>
                        </annotation>
                    </element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="GeosyntheticPropertyType">
        <sequence>
            <element ref="diggs:Geosynthetic"/>
        </sequence>
        <attributeGroup ref="gml:OwnershipAttributeGroup"/>
        <attributeGroup ref="gml:AssociationAttributeGroup"/>
    </complexType>
</schema>
