<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:diggs="http://diggsml.org/schemas/3"
    xmlns:gml="http://www.opengis.net/gml/3.2"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:maxVersion="1.1" vc:minVersion="1.0"
    elementFormDefault="qualified" targetNamespace="http://diggsml.org/schemas/3" version="3.1.0">


    <import namespace="http://www.opengis.net/gml/3.2" schemaLocation="gml3.2Profile_diggs.xsd"/>
    <element name="LocalCartesianCRS" substitutionGroup="gml:AbstractSingleCRS"
        type="diggs:LocalCartesianCRSType">
        <annotation>
            <documentation>
                A local Cartesian coordinate reference system that is tied to a spatial coordinate
                reference system. In addition to the coordinate system and datum of a GML
                engineering CRS, it gives the spatial location of its origin and the spatial
                location and direction of each axis, so that local coordinates can be transformed to
                spatial coordinates.
            </documentation>
        </annotation>
    </element>
    <complexType name="LocalCartesianCRSType">
        <complexContent>
            <extension base="gml:AbstractCRSType">
                <sequence>
                    <element ref="gml:cartesianCS">
                        <annotation>
                            <documentation>
                                The Cartesian coordinate system that defines the axes of this CRS.
                                It must be a Cartesian coordinate system, not a spherical,
                                cylindrical or other type.
                            </documentation>
                        </annotation>
                    </element>
                    <element ref="gml:engineeringDatum">
                        <annotation>
                            <documentation>
                                The engineering datum that defines the anchor point and
                                realization of this local coordinate reference system.
                            </documentation>
                        </annotation>
                    </element>
                    <element name="originLocation" type="diggs:PointLocationPropertyType">
                        <annotation>
                            <documentation>
                                The spatial location of the origin (0,0,0) of this local CRS, in a
                                recognized spatial coordinate reference system. It anchors the
                                transformation from local to spatial coordinates.
                            </documentation>
                        </annotation>
                    </element>
                    <element name="axisLocation" type="diggs:AxisLocationPropertyType" minOccurs="1"
                        maxOccurs="unbounded">
                        <annotation>
                            <documentation>
                                The spatial extent and direction of one axis of the Cartesian
                                coordinate system. Give one for each axis, in the axis order of the
                                Cartesian coordinate system.
                            </documentation>
                        </annotation>
                    </element>
                    <element name="transformationMethod" type="gml:CodeType" minOccurs="0">
                        <annotation>
                            <documentation>
                                The mathematical method used to transform between this local CRS and
                                spatial coordinates, for example affine, helmert,
                                direct-linear-referencing or polynomial. No DIGGS-authored
                                dictionary currently exists for this element.
                            </documentation>
                        </annotation>
                    </element>
                    <element name="rotationAngle" type="diggs:PlaneAngleMeasureType" minOccurs="0"
                        maxOccurs="3">
                        <annotation>
                            <documentation>
                                The angle that orients the local axes relative to the spatial
                                coordinate system. Give one angle for a 2D system (rotation about
                                the vertical axis) and up to three for a 3D system (for example
                                Euler angles, or rotations about the X, Y and Z axes);
                                transformationMethod determines how multiple angles are interpreted.
                                Repeat for each angle.
                            </documentation>
                        </annotation>
                    </element>
                    <element name="scaleFactor" type="double" minOccurs="0" default="1.0">
                        <annotation>
                            <documentation>
                                The uniform scale factor of the local coordinate system relative to
                                the spatial coordinate system. The default is 1.0 (no scaling). A
                                value above 1.0 means local coordinates represent larger distances
                                than the corresponding spatial coordinates, and a value below 1.0
                                smaller distances.
                            </documentation>
                        </annotation>
                    </element>
                    <element name="transformationAccuracy" type="diggs:LengthMeasureType"
                        minOccurs="0">
                        <annotation>
                            <documentation>
                                The expected positional error, as a distance, when transforming
                                coordinates between this local CRS and spatial coordinates.
                            </documentation>
                        </annotation>
                    </element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <element name="AxisLocation" type="diggs:AxisLocationType">
        <annotation>
            <documentation>
                The spatial location and orientation of one axis of a local Cartesian coordinate
                system, in the spatial coordinate reference system or as a unit vector in the units
                of that system. It positions the axis so that local coordinates can be transformed.
            </documentation>
        </annotation>
    </element>
    <complexType name="AxisLocationType">
        <complexContent>
            <extension base="diggs:AbstractComponentObjectBaseType">
                <sequence>
                    <element name="axisRef" type="gml:ReferenceType">
                        <annotation>
                            <documentation>
                                The axis being defined: normally the gml:id of a
                                gml:CoordinateSystemAxis in the Cartesian coordinate system of the
                                parent diggs:LocalCartesianCRS, for example X, Y, Z, easting,
                                northing, elevation, station or offset.
                            </documentation>
                        </annotation>
                    </element>
                    <element name="axisOrder" type="positiveInteger">
                        <annotation>
                            <documentation>
                                The position of this axis in the Cartesian coordinate system
                                definition: 1 for the first axis, 2 for the second, and so on. It
                                matches each axis to its spatial extent when the axis order is not
                                alphabetical.
                            </documentation>
                        </annotation>
                    </element>
                    <choice>
                        <sequence>
                            <element name="location" type="diggs:LinearExtentPropertyType"
                                minOccurs="1">
                                <annotation>
                                    <documentation>
                                        The spatial direction and extent of this axis, as a
                                        diggs:LinearExtent in the spatial coordinate reference
                                        system. Its start point typically corresponds to the origin
                                        location of the parent CRS, and the vector from start to end
                                        gives the positive direction and length of the axis. Give
                                        either this with an optional directionVector, or
                                        directionVector alone.
                                    </documentation>
                                </annotation>
                            </element>
                            <element name="directionVector" type="gml:VectorType" minOccurs="0">
                                <annotation>
                                    <documentation>
                                        A unit vector giving the direction of this axis in spatial
                                        coordinates, with components corresponding to the axes of
                                        the spatial CRS (typically X, Y, Z or easting, northing,
                                        elevation). Given with location, it supplements the linear
                                        extent and must be consistent with it.
                                    </documentation>
                                </annotation>
                            </element>
                            <element name="originOffset" type="double" minOccurs="0">
                                <annotation>
                                    <documentation>
                                        The value of the axis at its origin.
                                    </documentation>
                                </annotation>
                            </element>
                        </sequence>
                        <sequence>
                            <element name="directionVector" type="gml:VectorType" minOccurs="1">
                                <annotation>
                                    <documentation>
                                        A unit vector giving the direction of this axis in spatial
                                        coordinates, with components corresponding to the axes of
                                        the spatial CRS (typically X, Y, Z or easting, northing,
                                        elevation). Used when location is not given.
                                    </documentation>
                                </annotation>
                            </element>
                            <element name="originOffset" type="double" minOccurs="0">
                                <annotation>
                                    <documentation>
                                        The value of the axis at its origin.
                                    </documentation>
                                </annotation>
                            </element>
                        </sequence>
                    </choice>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="AxisLocationPropertyType">
        <annotation>
            <documentation>
                Property type that contains one diggs:AxisLocation object inline, or refers to one
                with xlink:href.
            </documentation>
        </annotation>
        <sequence minOccurs="0">
            <element ref="diggs:AxisLocation"/>
        </sequence>
        <attributeGroup ref="gml:AssociationAttributeGroup"/>
    </complexType>
</schema>
